services:
  postgres:
    image: postgres:16
    container_name: cs03-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_cs03:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: cs03-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata_cs03:/data/db

volumes:
  pgdata_cs03:
  mongodata_cs03:
